version: "3.5"
services:
  web:
    image: nginx:1.18-alpine
    ports:
      - target: 80
        published: 8080
        protocol: tcp
        mode: host
    volumes:
      - ./volumes:/mounted
      - ./web/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - db
  db:
    build: ./build/mysql
    volumes:
      - db-store:/var/lib/mysql
  app:
    build: ./build/app
    ports:
      - "10080:80"
    volumes:
      - ./volumes:/mounted
    depends_on:
      - web
volumes:
  db-store:
